"""initial_tables

Revision ID: ca52dfcce72d
Revises: 
Create Date: 2026-03-17 20:15:15.405922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca52dfcce72d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_youtube_channel_id'), 'creators', ['youtube_channel_id'], unique=True)
    op.create_table('creator_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysis_status'), nullable=False),
    sa.Column('youtube_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('instagram_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('trends_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('news_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('social_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('life_events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('controversy_signals', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('forecast', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_proxy', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_analyses_creator_id'), 'creator_analyses', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_analyses_creator_id'), table_name='creator_analyses')
    op.drop_table('creator_analyses')
    op.drop_index(op.f('ix_creators_youtube_channel_id'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
